In [42]:
import numpy as np
from scipy.optimize import fmin_l_bfgs_b as minimize
def costgrad(x, a):
    cost = np.sum((x-a)**2)
    grad = 2 * (x-a)
    return cost, grad

In [43]:
a = np.array([1,2])
x = np.random.randn(2)
optx, cost, messages = minimize(costgrad, x, args=[a])

In [44]:
print(optx, cost, messages)

[1. 2.] 4.930380657631324e-32 {'grad': array([ 0.0000000e+00, -4.4408921e-16]), 'task': b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL', 'funcalls': 3, 'nit': 2, 'warnflag': 0}


In [45]:
print(np.random.randn(3))

[-0.03217588  0.59214651 -0.88610655]


In [ ]:
cost = np.sum((np.matmul(x,w.transpose) -y)**2)/2/n + np.sum(w**2) *lamda / 2
    grad = lamda *w + np.matmul(np.matmul(x, x.transpose()), w) / n - np.matmul(x.transpose(), y) / n
    

In [54]:
data = np.genfromtxt('linear.csv', delimiter=',')
ttx = data[:3, 1:]
tty = data[:3, 0]
ttw = np.random.randn(4)
print(ttx)
print(tty)
print(ttw)

[[-1.47752373 -0.0502532  -0.17023633  1.        ]
 [ 0.90709037  0.66451566  0.47865149  1.        ]
 [ 0.4003217   0.43267376 -0.43504849  1.        ]]
[-1.13933054 -1.3895628  -1.46427865]
[-0.70528183 -0.64944129  0.17752787  0.4684145 ]


In [58]:
print(np.matmul(ttx, ttw))

[ 1.51289996 -0.51792978 -0.17215455]


In [67]:
print(np.sum((np.matmul(ttx, ttw)-tty)**2)/2/4 + np.sum(ttw**2)*lamda/2)

1.270716284799029


In [80]:
# print(np.matmul(ttx, ttx.transpose()))
testtest = np.matmul(ttx.transpose(), ttx)
print(testtest)
ttt = np.matmul(testtest, ttw.transpose())
print(ttt)

[[ 3.16614678  0.85023473  0.51154903 -0.17011167]
 [ 0.85023473  0.63131303  0.13839227  1.04693622]
 [ 0.51154903  0.13839227  0.44735485 -0.12663334]
 [-0.17011167  1.04693622 -0.12663334  3.        ]]
[-2.77407191 -0.49468726 -0.43056282  0.82281563]
